### ISSUE TITLE
geocode broken

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#211]
@fchapoton looks like your change in 620ef117b8eed2f66bb98a1dfccece215f8906d0 – or one nearby it – broke updating the website. Can you fix this?

```
Traceback (most recent call last):
  File "scripts/geocode.py", line 277, in <module>
    out.writexml(utils.UnicodeFileWriter(open(geocode_xml_outfn, "w")), newl="\n")
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 804, in writexml
    _write_data(writer, attrs[a_name].value)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 298, in _write_data
    writer.write(data)
  File "/home/user/website/scripts/utils.py", line 27, in write
    self._file.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 16: ordinal not in range(128)
makefile:15: recipe for target 'templates/devs.html' failed
make: *** [templates/devs.html] Error 1 
```

**Comment by haraldschilly** [comment]
Oh I see, you made it compatible with newer python versions, and hence it no longer work with python 3.6. That's something that would be great to know in advance :-)
