### ISSUE TITLE
sagecell eval examples no longer load

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#220]
this page did work in the past. something must have changed with the sagecell embedding script.

https://www.sagemath.org/eval.html and in particular

https://github.com/sagemath/website/blob/master/src/eval/eval.js

error:

```

S.Deferred.exceptionHook @ embedded_sagecell.js:2834
embedded_sagecell.js:2834 jQuery.Deferred exception: jQuery.getJSON(...).error is not a function TypeError: jQuery.getJSON(...).error is not a function
    at HTMLDocument.<anonymous> (https://www.sagemath.org/eval/eval.js:73:5)
    at e (https://sagecell.sagemath.org/embedded_sagecell.js:2834:30005)
    at t (https://sagecell.sagemath.org/embedded_sagecell.js:2834:30307) undefined
S.Deferred.exceptionHook @ embedded_sagecell.js:2834
ssl.google-analytics.com/ga.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
embedded_sagecell.js:2834 Uncaught TypeError: sagecell.init is not a function
    at initSageCell (eval.js:19)
    at HTMLDocument.<anonymous> (eval.js:36)
    at e (embedded_sagecell.js:2834)
    at t (embedded_sagecell.js:2834)
```

**Comment by slel** [comment]
@novoselt

**Comment by haraldschilly** [comment]
it's definitely very old code. I don't even know if the bug is in the website's script or the embedding code from sagecell. Maybe it's just a tiny fix. 🤷🏻

**Comment by novoselt** [comment]
As I recall, you had to pick items in the menu and THEN some SageCell will be populated and processed. At the moment it seems that the menu is not populated. My random guess also is that most of the code will not work because of print issue. This page existed before interact website was up and the latter was shut down quite a while ago too. It is awesome to have a big and organized collection of interacts, but so far we have failed to maintain it properly.

As far as sagecell embedding script, I was always trying to make sure that changes are backwards compatible and while there are some exotic situations with LMS where things change, the rest was working fine on the JavaScript side, as far as I am aware.

**Comment by kcrisman** [comment]
>
>
> As I recall, you had to pick items in the menu and THEN some SageCell will
> be populated and processed. At the moment it seems that the menu is not
> populated. My random guess also is that most of the code will not work
> because of print issue. This page existed before interact website was up
> and the latter was shut down quite a while ago too. It is awesome to have a
> big and organized collection of interacts, but so far we have failed to
> maintain it properly.
>
 Though on a related note, see http://sage-cell-repository.wikidot.com
